USE DATABASE ECOMMERCE_DB;
USE SCHEMA PUBLIC;

CREATE OR REPLACE TABLE RAW_TRANSACTIONS (
    INVOICE_NO VARCHAR(20),
    STOCK_CODE VARCHAR(20),
    DESCRIPTION VARCHAR(200),
    QUANTITY INT,
    INVOICE_DATE VARCHAR(50),
    UNIT_PRICE FLOAT,
    CUSTOMER_ID VARCHAR(20),
    COUNTRY VARCHAR(50)
);

CREATE OR REPLACE TABLE CLEANED_TRANSACTIONS (
    INVOICE_NO VARCHAR(20),
    STOCK_CODE VARCHAR(20),
    DESCRIPTION VARCHAR(200),
    QUANTITY INT,
    INVOICE_DATE TIMESTAMP,
    UNIT_PRICE FLOAT,
    CUSTOMER_ID VARCHAR(20),
    COUNTRY VARCHAR(50),
    REVENUE FLOAT,
    YEAR INT,
    MONTH INT,
    DAY_OF_WEEK VARCHAR(20)
);